# Generated by Django 5.2.4 on 2025-07-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('ml', 'Machine Learning'), ('ai', 'Artificial Intelligence'), ('ar', 'Augmented Reality'), ('sd', 'Software Development')], max_length=2),
        ),
    ]
