# Generated by Django 5.2.4 on 2025-07-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_contact_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='picture',
        ),
    ]
